### ISSUE TITLE
Please create Cocoapod spec.

### ISSUE THREAD

**Issue by mecid** [MaxHasADHD/TraktKit#2]

**Comment by alexk403** [comment]
This is a trivial question I'm sure but until a cocoapod is created, how would we integrate TraktKit into our own swift application? Thanks

**Comment by MaxHasADHD** [comment]
Hi there, I have not created a pod spec because I am not really familiar with that or anything of the like. To implement TraktKit you can either
1) Drag the .xcodeproj file into your project and add it as a dependency and embedded framework.
or 2) Drag all of the Swift files into your project.

I recommend #1, its easiest.

**Comment by puelocesar** [comment]
I'm trying the first, but I keep getting "No such module TrackKit", when trying "import TrackKit" on my Swift code

**Comment by MaxHasADHD** [comment]
CocoaPods is now supported!
